[package]
name = "caci_core"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serde = { version = "1.0.207", features = ["derive"] }
thiserror = "1.0.63"
toml_edit = { version = "0.22.20", features = ["serde"] }
