[package]
name = "caci_cli"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
caci_core = { version = "0.0.0", path = "../caci_core" }
caci_fs = { version = "0.0.0", path = "../caci_fs" }